### ISSUE TITLE
PyTorch and live transcription with mic

### ISSUE THREAD

**Issue by ramkumarkoppu** [usefulsensors/moonshine#15]
Hi,

Awesome work! I would like to use just PyTorch and skip Keras installation and with the Mac mic for live transcription instead of using recording audio clip, how do I do that please?

**Comment by keveman** [comment]
The inference code is written in Keras, so you can't skip Keras installation. However, the default installation uses the PyTorch backend. And Keras library itself does not depend on other software such as TensorFlow or JAX.

**Comment by ramkumarkoppu** [comment]
and how do I use mic on Mac/Ubuntu for live? the example code on the read me is using recorded audio file

**Comment by keveman** [comment]
The `transcribe` function accepts a filename or a `KerasTensor`. You can create a `KerasTensor` from a numpy array or a Torch Tensor.

**Comment by keveman** [comment]
Closing as there are no actionable followups.
