### ISSUE TITLE
Training code / methods?

### ISSUE THREAD

**Issue by julialongtin** [usefulsensors/moonshine#20]
Is the code / methods used during training available?

**Comment by evmaki** [comment]
Hi! We're not releasing our training code at this time, however the [arxiv paper](https://arxiv.org/abs/2410.15608) should include sufficient detail for you to replicate it.

**Comment by loretoparisi** [comment]
+1 for fine-tune code!

**Comment by evmaki** [comment]
No further action, so I'm closing this. We'll keep #23 open for discussion about fine-tuning.
