### ISSUE TITLE
Unused local variable

### ISSUE THREAD

**Issue by esadek** [usefulsensors/moonshine#26]
This `value_cache` local variable is assigned to but never used. Should it be removed?

https://github.com/usefulsensors/moonshine/blob/021e3943fe4cf4e7b3d31a04ee49794b5a45743d/moonshine/model.py#L335

**Comment by keveman** [comment]
`keras.layers.MultiHeadAttention`'s `compute_output_spec` doesn't like spurious keys such as `key_cache` and `value_cache` in `kwargs` unfortunately. So I have to pop them in the child class before calling the parent class. I can of course use not store them in a variable, or have a comment, but PR welcome too :)
