### ISSUE TITLE
Support Chinese?

### ISSUE THREAD

**Issue by MonolithFoundation** [usefulsensors/moonshine#33]
Support Chinese?

**Comment by evmaki** [comment]
Moonshine only supports English at this time. Other languages can be supported, provided you have the data – see #23 for discussion about fine-tuning to support other languages. Closing due to no further action.

**Comment by thewh1teagle** [comment]
@evmaki 
Could you add the list of supported languages to the main README? 
The only place I could know is is here. now I know - it support only English. Will be useful for others to see it in the main README.
Thanks!
