### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by surfmore** [usefulsensors/moonshine#35]
Can anyone help me with this error? I just run the installation as in the instructions, but using conda enviroment instead of uv

(Moonshine) PS D:\Google Drive\coding\moonshine> pip install useful-moonshine[tensorflow]@git+https://github.com/usefulsensors/moonshine.git   
Collecting useful-moonshine@ git+https://github.com/usefulsensors/moonshine.git (from useful-moonshine[tensorflow]@ git+https://github.com/usefulsensors/moonshine.git)
  Cloning https://github.com/usefulsensors/moonshine.git to c:\users\user\appdata\local\temp\pip-install-2o1uu6aa\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8
  Running command git clone --filter=blob:none --quiet https://github.com/usefulsensors/moonshine.git 'C:\Users\user\AppData\Local\Temp\pip-install-2o1uu6aa\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8'
  Resolved https://github.com/usefulsensors/moonshine.git to commit 88230f0a5b74c93f20811d7e14a032dd411dad2e
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      C:\Users\user\AppData\Local\Temp\pip-install-2o1uu6aa\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8\setup.py:3: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
          exec(compile('''
          ~~~~^^^^^^^^^^^^
          # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ...<31 lines>...
          exec(compile(setup_py_code, filename, "exec"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
          ''' % ('C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-2o1uu6aa\\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8\\setup.py',), "<pip-setuptools-caller>", "exec"))   
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-2o1uu6aa\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8\setup.py", line 15, in <module>
          version=read_version(),
                  ~~~~~~~~~~~~^^
        File "C:\Users\user\AppData\Local\Temp\pip-install-2o1uu6aa\useful-moonshine_35d909ee184b41f2b0eb09bb569772e8\setup.py", line 9, in read_version
          return locals()["__version__"]
                 ~~~~~~~~^^^^^^^^^^^^^^^
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by surfmore** [comment]
found the error. I was using the newest python version that it does not work with. Please close.

**Comment by evmaki** [comment]
Thanks for updating with your solution. Closing now.
