### ISSUE TITLE
torch model

### ISSUE THREAD

**Issue by wangyifan2018** [usefulsensors/moonshine#41]
Hello, I am currently trying to run this model on hardware other than a GPU. I attempted to convert it to ONNX using Keras, but found that it is not well-supported on our hardware. Do you have a model.py file for PyTorch that we could modify to better suit our needs?

**Comment by njeffrie** [comment]
I have been working to support Huggingface Transformers, and I created with a [pytorch implementation](https://huggingface.co/njeffrie/moonshine-tiny/blob/main/modeling_moonshine.py) in [this test Huggingface Hub repo](https://huggingface.co/njeffrie/moonshine-tiny).

**Comment by wangyifan2018** [comment]
Thanks for your support. This is an amazing model, and we will continue to try.

**Comment by wangyifan2018** [comment]
We successfully ran the ONNX model converted from Torch on the device, achieving much better performance than Whisper. Amazing work! If it’s convenient for you, could you also help provide the base version of the model later? Thank you very much.

**Comment by njeffrie** [comment]
Please check out our official Huggingface Hub [tiny](https://huggingface.co/UsefulSensors/moonshine-tiny) and [base](https://huggingface.co/UsefulSensors/moonshine-base) models.

**Comment by evmaki** [comment]
No further action, closing this issue.
