### ISSUE TITLE
Plans / potential for browser use?

### ISSUE THREAD

**Issue by nmstoker** [usefulsensors/moonshine#57]
I saw that there's an Onnx Runtime example - that made me wonder whether it might be feasible to run a version of the model in the browser.

https://github.com/usefulsensors/moonshine/tree/5689bdf58818d26029cb59a9f25b186f8971e4a9/moonshine/demo#demo-standalone-file-transcription-with-onnx

Are there any plans to port moonshine for browser use? And have you any comment on how challenging that might be. I guess if there are python dependencies which are hard to replace with JavaScript equivalents it might be pretty difficult, unless perhaps Pyodide might bridge the gap?

**Comment by keveman** [comment]
Yes, we have a demo of Moonshine running in the browser using [onnxruntime-web](https://onnxruntime.ai/docs/tutorials/web/). We will be releasing it soon, stay tuned.

**Comment by curiositry** [comment]
@keveman This is fantastic. My long term roadmap for the project I'm working on porting from Whisper.cpp to Moonshine involves a version that runs clientside (WASM?) in the browser.

**Comment by nmstoker** [comment]
Many thanks @keveman - this is great news, really looking forward to seeing that new demo!

**Comment by csukuangfj** [comment]
@nmstoker  @curiositry 

FYI: We have already supported running Moonshine models (and other models like Whisper, etc) with WebAssembly. You can run them either using NodeJS on the server side or directly in your browser locally on the client side.

The following huggingface space is a demo
https://huggingface.co/spaces/k2-fsa/web-assembly-vad-asr-sherpa-onnx-en-moonshine-tiny

<img width="1440" alt="Screenshot 2024-11-13 at 21 00 06" src="https://github.com/user-attachments/assets/5199239f-5fe4-4bac-8af0-643499a4eeaf">


Please see also https://github.com/k2-fsa/sherpa-onnx/pull/1535

**Comment by evmaki** [comment]
@nmstoker @curiositry I just made our web demo public in a [HuggingFace space](https://huggingface.co/spaces/UsefulSensors/moonshine-web). It uses `onnxruntime-web` to perform inferences in the browser. We will also be merging the source for the demo into main shortly; it includes the JavaScript port of Moonshine ONNX model inferences. This should hopefully provide a good starting point for building out your own web applications.

**Comment by nmstoker** [comment]
Thank you @evmaki - that's kind of you to follow up and to include [the source](https://github.com/usefulsensors/moonshine/tree/main/moonshine/demo/moonshine-web).

The HF demo works really well online. I'll give it a whirl integrating with my dev site this weekend - looking forward to it!

Will close this now. Thanks again!
